import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import movies from "@/../public/movies.json"
import { AuthProvider } from "@/context/authContext";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400","500","600","700"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`}
      >
        <AuthProvider>
        <>
        <Navbar />
        <div>{children}</div>
        </>
        </AuthProvider>
      </body>
    </html>
  );
}
